package com.example.helloworldcompose.ui.theme

import androidx.compose.ui.graphics.Color

// Neutrals / Surfaces (parchment-toned paper stock)
val Surface = Color(0xFFF7F9FB)
val SurfaceDim = Color(0xFFD8DADC)
val SurfaceBright = Color(0xFFF7F9FB)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF2F4F6)
val SurfaceContainer = Color(0xFFECEEF0)
val SurfaceContainerHigh = Color(0xFFE6E8EA)
val SurfaceContainerHighest = Color(0xFFE0E3E5)
val OnSurface = Color(0xFF191C1E)
val OnSurfaceVariant = Color(0xFF45474C)
val InverseSurface = Color(0xFF2D3133)
val InverseOnSurface = Color(0xFFEFF1F3)
val SurfaceVariant = Color(0xFFE0E3E5)
val SurfaceTint = Color(0xFF545F73)
val Outline = Color(0xFF75777D)
val OutlineVariant = Color(0xFFC5C6CD)
val Background = Color(0xFFF7F9FB)
val OnBackground = Color(0xFF191C1E)

// Primary — Deep Ink Slate (structural framing, primary actions)
val Primary = Color(0xFF091426)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF1E293B)
val OnPrimaryContainer = Color(0xFF8590A6)
val InversePrimary = Color(0xFFBCC7DE)
val PrimaryFixed = Color(0xFFD8E3FB)
val PrimaryFixedDim = Color(0xFFBCC7DE)
val OnPrimaryFixed = Color(0xFF111C2D)
val OnPrimaryFixedVariant = Color(0xFF3C475A)

// Secondary — Soft Indigo/Violet (interactive focal points, accents)
val Secondary = Color(0xFF4B41E1)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFF645EFB)
val OnSecondaryContainer = Color(0xFFFFFBFF)
val SecondaryFixed = Color(0xFFE2DFFF)
val SecondaryFixedDim = Color(0xFFC3C0FF)
val OnSecondaryFixed = Color(0xFF0F0069)
val OnSecondaryFixedVariant = Color(0xFF3323CC)

// Tertiary — Mint Green (progression, completion, streak feedback)
val Tertiary = Color(0xFF00190E)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF00301E)
val OnTertiaryContainer = Color(0xFF00A472)
val TertiaryFixed = Color(0xFF6FFBBE)
val TertiaryFixedDim = Color(0xFF4EDEA3)
val OnTertiaryFixed = Color(0xFF002113)
val OnTertiaryFixedVariant = Color(0xFF005236)

// Error
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
